rootProject.name = "RickAndMorty"
include(":app")
include(":resources")
include(":common")
include(":domain")
include(":data")
include(":navigation")
include(":feature_character")
include(":feature_character:characters")
include(":feature_character:character_details")
include(":feature_location")
include(":feature_location:locations")
include(":feature_episode")
include(":feature_episode:episodes")
